#!/usr/bin/env bash
# a comment
default=/etc/nginx/sites_available/default
sudo apt update
sudo apt install nginx -y
echo "Hello World!" | sudo tee $index_file &&
sudo chmod 644 $index_file
sudo chmod a+w $default &&
sudo sed -i '/server_name _;/a\\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me https://google.com permanent;\n\t}\n' $default_web &&
sudo chmod 644 $default &&
sudo service nginx restart
