#!/usr/bin/env bash
# setup a 404 page
index_file=/var/www/html/index.nginx-debian.html
default=/etc/nginx/sites-available/default
error_file=/var/www/html/error.html
sudo apt update
sudo apt install nginx -y
echo "Hellow World!" | sudo tee $index_file &&
sudo chmod 644 $index_file
sudo chmod a+w $default &&
sudo sed -i '/server_name _;/a\\n\terror_page 404 /error.html;\n\tlocation /error.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me https://google.com permanent;\n\t}\n' "$default" &&
sudo chmod 644 "$default"
sudo touch $error_file
sudo chmod a+w $error_file
sudo echo "Ceci n'est pas une page" | sudo tee $error_file
sudo chmod 644 $error_file
sudo service nginx restart
