#!/usr/bin/env bash
#check the connectivity of an ip address
if [[ $# -eq 0 ]]
then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
    for (( i=0 ; i<5 ; i++ )); do
	ping "$1"
    done
fi
