#!/usr/bin/env bash
# configure an nginx server
kill -15 "$(cat var/run/nginx.pid)"
config_data=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /usr/share/nginx/html;
	index index.html index.htm;

	server_name localhost;
"
echo "$config_data" > /etc/nginx/sites-available/default
sudo service nginx restart
