#!/usr/bin/env bash
#say hi using while

counter=1
while [ "$counter" -lt 10 ]
do
    if (( counter == 9 ))
    then
        echo 'Best School'
	echo 'Hi'
	(( counter += 1 ))
    fi
    echo 'Best School'
    (( counter += 1 ))
done
