#!/usr/bin/env bash
#check luck using while
counter=1
while [ "$counter" -le 10 ]
do
    if (( counter == 4 ))
    then
	echo 'bad luck'
    elif (( counter == 8 ))
    then
	echo 'good luck'
    else
	echo 'Best School'
    fi
    let "counter = $counter + 1"
done
