#!/usr/bin/env bash
#display a 12 hour clock
hour=0

while [ "$hour" -le 12 ]
do
    echo "Hour: $hour"
    min=1
    while [ "$min" -lt 60 ]
    do
	echo "$min"
	(( min += 1 ));
    done
    ((hour += 1 ));
done
